spring:
  application:
    name: my-crawlew
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    ttlInMinutes: 60
  data:
    mongodb:
      uri: mongodb://localhost:27017/my-crawlew
      auto-index-creation: true
    redis:
      repositories:
        enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1
    consumer:
      group-id: ${spring.application.name}
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      retries: 10
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
springdoc:
  pathsToMatch: /api/**